package spring.mvc;
// Generated Oct 27, 2021 10:35:19 AM by Hibernate Tools 4.3.1



/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private int empId;
     private String empName;
     private String designation;
     private String salary;

    public Employee() {
    }

	
    public Employee(int empId) {
        this.empId = empId;
    }
    public Employee(int empId, String empName, String designation, String salary) {
       this.empId = empId;
       this.empName = empName;
       this.designation = designation;
       this.salary = salary;
    }
   
    public int getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(int empId) {
        this.empId = empId;
    }
    public String getEmpName() {
        return this.empName;
    }
    
    public void setEmpName(String empName) {
        this.empName = empName;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getSalary() {
        return this.salary;
    }
    
    public void setSalary(String salary) {
        this.salary = salary;
    }




}


